version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - /mnt/esdata:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
  kibana:
    image: kibana:7.12.0
    depends_on:
      - elasticsearch
    ports:
      - "127.0.0.1:5601:5601"
    deploy:
      mode: replicated
      replicas: 1
  logstash:
    image: logstash:7.12.0
    ports:
      - "127.0.0.1:5044:5044"
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.0
    user: root
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: [ "--strict.perms=false" ]



