version: '3.3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
    volumes:
      - /mnt/esdata:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    configs:
      - source: elastic_conf
        target: /usr/share/elasticsearch/config/elastic.yml
  kibana:
    image: kibana:7.12.0
    depends_on:
      - elasticsearch
    ports:
      - "127.0.0.1:5601:5601"
    deploy:
      mode: replicated
      replicas: 1
    links:
      - elasticsearch:elasticsearch
    configs:
      - source: kibana_conf
        target: /usr/share/kibana/config/kibana.yml
  logstash:
    container_name: logstash
    image: logstash:7.12.0
    ports:
      - "127.0.0.1:5044:5044"
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
    links:
      - elasticsearch:elasticsearch
    configs:
      - source: logstash_config
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: logstash_yml
        target: usr/share/logstash/config/logstash.yml
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.0
    user: root
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
    links: logstash:logstash
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    command: [ "--strict.perms=false" ]

configs:
  filebeat_config:
    file: ./filebeat.yml
  logstash_config:
    file: ./logstash.conf
  elastic_conf:
    file: ./elasticsearch.yml
  logstash_yml:
    file: ./logstash.yml
  kibana_conf:
    file: ./kibana.yml



