version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - /mnt/esdata:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
  kibana:
    image: kibana:7.12.0
    depends_on:
      - elasticsearch
    ports:
      - "127.0.0.1:5601:5601"
    deploy:
      mode: replicated
      replicas: 1
  logstash:
    image: logstash:7.12.0
    ports:
      - "127.0.0.1:12201:12201/udp"
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /mnt/logstash-pipeline:/usr/share/logstash/pipeline/

