version: "3"

services:
  webserver:
    image: php:5.6-apache
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - database
    volumes: 
      - /mnt/www:/var/www/html
      - /mnt/config/php/php.ini:/usr/local/etc/php/php.ini
      - /mnt/config/vhosts:/etc/apache2/sites-enabled
      - /mnt/logs/apache2:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      PMA_PORT: 8080
      MYSQL_ROOT_PASSWORD: tiger
    deploy:
      mode: replicated
      replicas: 2
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  database:
    image: mysql:8
    restart: 'always'
    ports:
      - "127.0.0.1:3306:3306"
    volumes: 
      - /mnt/data/mysql:/var/lib/mysql
      - /mnt/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    deploy:
      mode: replicated
      replicas: 2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: tiger
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - '8080:80'
    volumes: 
      - /sessions
      - /mnt/config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    deploy:
      mode: replicated
      replicas: 2
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  memcached:
    image: memcached:latest
    ports:
      - "127.0.0.1:6379:6379"
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  nodejs:
    image: nodejs:latest
    ports:
      - "127.0.0.1:49160:8080"
    deploy:
      mode: replicated
      replicas: 1
